### PR TITLE
Added .editorconfig

### PR DESCRIPTION
**Pull request by szepeviktor**
This way GitHub displays leaner PHP code.

Please add the removal of this file to your release checklist.

### CODE REVIEW

**Comment by michaeluno** [comment]
Can we go with `indent_size = 4`?

**Comment by szepeviktor** [comment]
It is.

**Comment by michaeluno** [comment]
Ops. I wanted to say `indent_style = space`.

**Comment by szepeviktor** [comment]
This was for strict WPCS.
Closing now.

**Pull request closed without merging**
