### PR TITLE
Replacing ABSPATH to work on Wordpress.com servers.

### PR DESCRIPTION
**Pull request by mnajafzadeh**

### CODE REVIEW

**Comment by michaeluno** [comment]
Regarding the regular expression pattern, `/[\/\\\\]+wp-content(.*)/m` , 

- why do you need `+` before `wp-content`? It should be removed if there is no good reason.
- why do you need the multi-line modifier, `m`? In what case, `WP_CONTENT_DIR` holds a multi-line value? It should be removed if there is no good reason.. 
- why do you need `(.*)`? This will be a problem for rare cases that a user installs WordPress under a `wp-content` directory. It should be replaced with `$` if there is no good reason.

**Comment by mnajafzadeh** [comment]
Hi,

- I forgot to remove + before wp-content
- The same for /m :D
- I used (.*) in the expression to also include wp-content/ wp-content\ with slash or backslash at the end and for example have /host/src/wp-content/ replaced with /host/src not /host/src/
If I only add a $ the last trailing slash will stay there. I know it's not important but just to make it clean.

Thank you

**Comment by mnajafzadeh** [comment]
Please, check this example https://regex101.com/r/QVdhlX/1
You can see if I use [\/\\]wp-content$ it will not work for:
/host/src/wp-content/

Regards

**Comment by michaeluno** [comment]
The default definition of `WP_CONTENT_DIR` does not contain a trailing slash (https://github.com/WordPress/WordPress/blob/5.2.1/wp-includes/default-constants.php#L72, https://github.com/WordPress/WordPress/blob/5.2.1/wp-load.php#L68) So you are talking about a case that `WP_CONTENT_DIR` has a user-defined custom definition with a trailing slash. 

Then I'd suggest `preg_replace( '/[\/\\\\]wp-content$/', '', rtrim( WP_CONTENT_DIR, '/\\' ) )`.

**Comment by mnajafzadeh** [comment]
Great!
I use your suggestion.

**Pull request closed without merging**
